// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtbpL3e9w_RC_Q8Uqb2C720tyoY3Rg9o',
    appId: '1:405821752852:web:2f9d47b0c07879df0c8901',
    messagingSenderId: '405821752852',
    projectId: 'busmap-3b0c1',
    authDomain: 'busmap-3b0c1.firebaseapp.com',
    storageBucket: 'busmap-3b0c1.firebasestorage.app',
    measurementId: 'G-3ZPY28ZM33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD32cBVxtbJJlcFKEHUSsNF5tO9Y51k3oY',
    appId: '1:405821752852:android:ff62bb314d4ee9520c8901',
    messagingSenderId: '405821752852',
    projectId: 'busmap-3b0c1',
    storageBucket: 'busmap-3b0c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7dGq_MB8iYii91sC9EDvHsvImiSL8R80',
    appId: '1:405821752852:ios:63e849876e1c78280c8901',
    messagingSenderId: '405821752852',
    projectId: 'busmap-3b0c1',
    storageBucket: 'busmap-3b0c1.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7dGq_MB8iYii91sC9EDvHsvImiSL8R80',
    appId: '1:405821752852:ios:63e849876e1c78280c8901',
    messagingSenderId: '405821752852',
    projectId: 'busmap-3b0c1',
    storageBucket: 'busmap-3b0c1.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMtbpL3e9w_RC_Q8Uqb2C720tyoY3Rg9o',
    appId: '1:405821752852:web:528bfe5bbbfeff130c8901',
    messagingSenderId: '405821752852',
    projectId: 'busmap-3b0c1',
    authDomain: 'busmap-3b0c1.firebaseapp.com',
    storageBucket: 'busmap-3b0c1.firebasestorage.app',
    measurementId: 'G-JR4G0M2NT7',
  );

  // Linux reutiliza as credenciais web (funciona para desenvolvimento)
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAMtbpL3e9w_RC_Q8Uqb2C720tyoY3Rg9o',
    appId: '1:405821752852:web:2f9d47b0c07879df0c8901',
    messagingSenderId: '405821752852',
    projectId: 'busmap-3b0c1',
    authDomain: 'busmap-3b0c1.firebaseapp.com',
    storageBucket: 'busmap-3b0c1.firebasestorage.app',
    measurementId: 'G-3ZPY28ZM33',
  );
}